### ISSUE TITLE
Hi,where is the file of 'BTRX_BTC-USDT_ohlcv.csv'? Thank you.

### ISSUE THREAD

**Issue by ascend2018** [karma0/rltrade#1]
FileNotFoundError: [Errno 2] File b'BTRX_BTC-USDT_ohlcv.csv' does not exist: b'BTRX_BTC-USDT_ohlcv.csv'

**Comment by karma0** [comment]
The file is something that you will have to bring on your own.  You should be able to provide any CSV with the columns `open`, `high`, `low`, `close`, and `volume`.
